### ISSUE TITLE
No such file or directory: 'data/zju_mocap/CoreView_394/lbs/bigpose_vertices.npy'

### ISSUE THREAD

**Issue by taconite** [zju3dv/animatable_nerf#15]
Hi, Sida

I was trying to extract mesh results for sequences 392, 393, and 394 for ZJU-MoCap dataset in order to do some comparison. Since 392, 393, 394 do not come with preprocessed lbs folder I just run tools/prepare_blend_weights.py to generate folder. However when generating meshes it still says "lbs/bigpose_vertices.npy" is missing. Could you share these files for 392, 393, 394 or the script that can generate this "bigpose_vertices.npy"?

Thanks!

**Comment by pengsida** [comment]
I do not see that the `tools/prepare_blend_weights.py` requires `bigpose_vertices.npy`.
Please check the code: https://github.com/zju3dv/animatable_nerf/blob/master/tools/prepare_blend_weights.py

**Comment by taconite** [comment]
It happens when I try to generate meshes. I first generate `data/zju_mocap/CoreView_394/lbs` folder using `tools/prepare_blend_weights.py`, then I train model for 394, then I run:
`python run.py --type visualize --cfg_file configs/aninerf_394.yaml exp_name aninerf_394 vis_posed_mesh True`

I got the following error
`Traceback (most recent call last):
  File "run.py", line 144, in <module>
    globals()['run_' + args.type]()
  File "run.py", line 96, in run_visualize
    for batch in tqdm.tqdm(data_loader):
  File "/home/sfwang/miniconda3/envs/animatable_nerf/lib/python3.7/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/sfwang/miniconda3/envs/animatable_nerf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/sfwang/miniconda3/envs/animatable_nerf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/sfwang/miniconda3/envs/animatable_nerf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/sfwang/miniconda3/envs/animatable_nerf/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sfwang/miniconda3/envs/animatable_nerf/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sfwang/miniconda3/envs/animatable_nerf/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sfwang/miniconda3/envs/animatable_nerf/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "lib/datasets/aninerf_mesh_dataset.py", line 136, in __getitem__
    tpose = np.load(vertices_path).astype(np.float32)
  File "/home/sfwang/miniconda3/envs/animatable_nerf/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/zju_mocap/CoreView_394/lbs/bigpose_vertices.npy'
`

**Comment by pengsida** [comment]
I updated the code.

**Comment by taconite** [comment]
Ah ok, so the 'bigpose_vertices.npy' and 'tvertices.npy' are the same? Thanks for the update!

**Comment by pengsida** [comment]
No. I uploaded another version of code previously.
